name: Run tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Meteor
        run: |
          curl "https://install.meteor.com/?release=3.3.2" | sh
          echo "$HOME/.meteor" >> $GITHUB_PATH

      - name: Install dependencies
        run: meteor npm ci

      - name: Run tests
        run: npm test
